### ISSUE TITLE
New XUnit Nuget testrunner does not detect Chill tests

### ISSUE THREAD

**Issue by scspijker** [Erwinvandervalk/Chill#28]
When I updated the xUnit test runner extension today, it told me it was deprecated and I needed to install the nuget test runner package. So I did, because then tests would also run on things like Visual Studio Online.

This resulted in all my Chill tests disappearing from the test explorer (NSpec still works fine). Any hints?

**Comment by Erwinvandervalk** [comment]
Hi, thank you for your question. 

I doubt this is an issue with Chill. Chill doesn't have a built in testrunner, so it relies on external ones, such as xUnit, NUnit or MsTest. If the testrunner doesn't detect the tests, it's likely something with the testrunner. 

Can you try to create a 'plain' xunit test, for example:
public class EmptyTest
{
[Fact]
public void DoSomething()
{
}
}

Does it find that test? If not, then it's likely due to the testrunner. 

Also, can you try to run your tests from the command line? 
https://xunit.codeplex.com/wikipage?title=HowToUse 

Let me know how things go..

**Comment by scspijker** [comment]
I also think it's probably the testrunner, it does not find the empty test. It is not really clear to me how to run the commandline runner (without installing ruby and compiling my own testrunner).

I'll to figure out why the xUnit test runner isn't working.
Thnx!
